name: "dataset-vuln-web-frameworks"
iterations: 5
topology:
  routers: 1
  hosts: 4
  randomize: false
services:
  enabled: true
  randomize: true
  count: [2, 4]
  include: ["HTTP"]
vulns:
  enabled: true
  randomize: true
  count: [1, 3]
  include: ["struts2"]
flag_node_generators:
  enabled: false
  count: 0
flows:
  enabled: false
  chain_length: 0
traffic:
  profile: light
  payload_types: [text]
segmentation:
  enabled: false
hitl:
  use_env: false
validation:
  policy: "strict"
  check_artifacts:
    enabled: true
    delay_seconds: 15
    strict: true
