name: "dataset-vuln-devops"
iterations: 5
topology:
  routers: [1, 2]
  hosts: [4, 6]
  randomize: true
services:
  enabled: true
  randomize: true
  count: [2, 4]
  include: ["SSH", "HTTP"]
vulns:
  enabled: true
  randomize: true
  count: [1, 2]
  include: ["jenkins"]
flag_node_generators:
  enabled: false
  count: 0
flows:
  enabled: false
  chain_length: 0
traffic:
  profile: medium
  payload_types: [text, photo]
segmentation:
  enabled: false
hitl:
  use_env: false
validation:
  policy: "strict"
  check_artifacts:
    enabled: true
    delay_seconds: 15
    strict: true
