name: "dataset-vuln-perimeter"
iterations: 5
topology:
  routers: 2
  hosts: [5, 7]
  randomize: true
services:
  enabled: true
  randomize: true
  count: [2, 5]
  include: ["HTTP"]
vulns:
  enabled: true
  randomize: true
  count: [1, 2]
  include: ["nginx"]
flag_node_generators:
  enabled: false
  count: 0
flows:
  enabled: false
  chain_length: 0
traffic:
  profile: medium
  payload_types: [text, audio]
segmentation:
  enabled: true
  density: 0.3
hitl:
  use_env: false
validation:
  policy: "strict"
