name: "dataset-vuln-perimeter"
iterations: 5
topology:
  routers: 2
  hosts: [5, 7]
  randomize: true
services:
  enabled: true
  randomize: true
  count: [2, 5]
  include: ["HTTP"]
vulns:
  enabled: true
  randomize: true
  count: 2
  include: ["nginx"]
flag_node_generators:
  enabled: false
  count: 0
flows:
  enabled: true
  chain_length: 2
  allow_duplicates: false
  include_all_topology_pivots: true
traffic:
  profile: medium
  payload_types: [text, audio]
segmentation:
  enabled: true
  density: 0.3
  accessible_by_pivot: true
  items:
    - type: Firewall
      count: 1
      pivot_enabled: true
      pivot_provider: vulnerability
hitl:
  use_env: false
validation:
  policy: "strict"
