name: "dataset-vuln-search-data"
iterations: 5
topology:
  routers: 2
  hosts: [5, 7]
  randomize: true
services:
  enabled: true
  randomize: true
  count: [2, 4]
  include: ["HTTP", "SSH"]
vulns:
  enabled: true
  randomize: true
  count: 3
  include: ["elasticsearch"]
flag_node_generators:
  enabled: false
  count: 0
flows:
  enabled: true
  chain_length: 3
  allow_duplicates: false
traffic:
  profile: medium
  payload_types: [text, video]
segmentation:
  enabled: true
  density: 0.4
  items:
    - type: NAT
      count: 1
      pivot_enabled: false
hitl:
  use_env: false
validation:
  policy: "strict"
  check_artifacts:
    enabled: true
    delay_seconds: 15
    strict: true
