name: "dataset-vuln-collaboration"
iterations: 5
topology:
  routers: 2
  hosts: [6, 8]
  randomize: true
services:
  enabled: true
  randomize: true
  count: [3, 5]
  include: ["SSH", "HTTP"]
vulns:
  enabled: true
  randomize: true
  count: 3
  include: ["confluence"]
flag_node_generators:
  enabled: false
  count: 0
flows:
  enabled: true
  chain_length: 3
  allow_duplicates: false
traffic:
  profile: heavy
  payload_types: [text, photo]
segmentation:
  enabled: true
  density: 0.35
  items:
    - type: Firewall
      count: 1
      pivot_enabled: false
hitl:
  use_env: false
validation:
  policy: "strict"
  check_artifacts:
    enabled: true
    delay_seconds: 15
    strict: true
