name: "dataset-mixed-data-caching"
iterations: 5
topology:
  routers: 2
  hosts: [6, 8]
  randomize: true
services:
  enabled: true
  randomize: true
  count: [3, 5]
  include: ["SSH", "HTTP"]
vulns:
  enabled: true
  randomize: true
  count: [1, 3]
  include: ["elasticsearch"]
flag_node_generators:
  enabled: true
  randomize: true
  count: 4
  include: ["Database:*", "Cache:*"]
flows:
  enabled: true
  chain_length: 5
  allow_duplicates: false
traffic:
  profile: medium
  payload_types: [photo, audio]
segmentation:
  enabled: true
  density: 0.4
  items:
    - type: NAT
      count: 1
      pivot_enabled: false
hitl:
  use_env: false
validation:
  policy: "strict"
