name: dataset-vuln-cache_run01
iterations: 1
seed: 1613141327
topology:
  routers: 1
  hosts: 4
services:
  enabled: true
  count: 2
  density: 1.0
  include:
  - SSH
  - HTTP
  exclude: []
traffic:
  enabled: true
  density: 0.6
  items:
  - type: TCP
    count: 1
    factor: 1.0
    pattern: continuous
    rate_kbps: 128.0
    period_s: 2.0
    jitter_pct: 15.0
    content_type: text
  - type: UDP
    count: 1
    factor: 1.0
    pattern: periodic
    rate_kbps: 64.0
    period_s: 5.0
    jitter_pct: 25.0
    content_type: gibberish
vulns:
  enabled: true
  count: 2
  specific:
  - name: redis/CVE-2022-0543
    count: 1
  - name: celery/celery3_redis_unauth
    count: 1
flag_node_generators:
  enabled: false
  count: 0
  include: []
  exclude: []
flows:
  enabled: true
  chain_length: 2
  allow_duplicates: false
  include_all_topology_pivots: false
segmentation:
  enabled: false
  density: 0.5
  items: []
hitl:
  use_env: false
validation:
  policy: strict
  check_artifacts:
    enabled: true
    delay_seconds: 15
    strict: true
