name: dataset-vuln-collaboration_run03
iterations: 1
seed: 1899008699
topology:
  routers: 2
  hosts: 7
services:
  enabled: true
  count: 4
  density: 1.0
  include:
  - SSH
  - HTTP
  exclude: []
traffic:
  enabled: true
  density: 0.85
  items:
  - type: TCP
    count: 2
    factor: 1.0
    pattern: continuous
    rate_kbps: 512.0
    period_s: 1.0
    jitter_pct: 10.0
    content_type: text
  - type: UDP
    count: 2
    factor: 1.0
    pattern: burst
    rate_kbps: 256.0
    period_s: 2.0
    jitter_pct: 20.0
    content_type: photo
vulns:
  enabled: true
  count: 3
  specific:
  - name: confluence/CVE-2022-26134
    path: /Users/jcacosta/Documents/GitHub/scenarioforge/outputs/installed_vuln_catalogs/05-27-26-14-40-12-f61521/content/vulhub/confluence/CVE-2022-26134/docker-compose.yml
    count: 1
  - name: confluence/CVE-2019-3396
    path: /Users/jcacosta/Documents/GitHub/scenarioforge/outputs/installed_vuln_catalogs/05-27-26-14-40-12-f61521/content/vulhub/confluence/CVE-2019-3396/docker-compose.yml
    count: 1
  - name: confluence/CVE-2023-22527
    path: /Users/jcacosta/Documents/GitHub/scenarioforge/outputs/installed_vuln_catalogs/05-27-26-14-40-12-f61521/content/vulhub/confluence/CVE-2023-22527/docker-compose.yml
    count: 1
flag_node_generators:
  enabled: false
  count: 0
  include: []
  exclude: []
flows:
  enabled: false
  chain_length: 0
  allow_duplicates: false
  include_all_topology_pivots: false
segmentation:
  enabled: true
  density: 0.35
  items: []
hitl:
  use_env: false
validation:
  policy: strict
