name: dataset-artifact-remote-access_run05
iterations: 1
seed: 337648091
topology:
  routers: 1
  hosts: 4
services:
  enabled: true
  count: 3
  density: 1.0
  include:
  - SSH
  exclude: []
traffic:
  enabled: true
  density: 0.35
  items:
  - type: TCP
    count: 1
    factor: 1.0
    pattern: periodic
    rate_kbps: 32.0
    period_s: 5.0
    jitter_pct: 10.0
    content_type: photo
vulns:
  enabled: false
  count: 0
  include: []
  exclude: []
flag_node_generators:
  enabled: true
  count: 1
  specific:
  - id: ssh_key_git_deploy
    name: 'SSH: Key Git Deploy Account'
    count: 1
flows:
  enabled: false
  chain_length: 0
  allow_duplicates: false
  include_all_topology_pivots: false
segmentation:
  enabled: false
  density: 0.5
  items: []
hitl:
  use_env: false
validation:
  policy: strict
