name: dataset-artifact-data-stores_run05
iterations: 1
seed: 597385051
topology:
  routers: 2
  hosts: 7
services:
  enabled: true
  count: 4
  density: 1.0
  include:
  - HTTP
  - SSH
  exclude: []
traffic:
  enabled: true
  density: 0.6
  items:
  - type: TCP
    count: 1
    factor: 1.0
    pattern: continuous
    rate_kbps: 128.0
    period_s: 2.0
    jitter_pct: 15.0
    content_type: photo
  - type: UDP
    count: 1
    factor: 1.0
    pattern: periodic
    rate_kbps: 64.0
    period_s: 5.0
    jitter_pct: 25.0
    content_type: video
vulns:
  enabled: false
  count: 0
  include: []
  exclude: []
flag_node_generators:
  enabled: true
  count: 4
  specific:
  - id: redis_exposed_keys
    name: 'Cache: Exposed Redis Keys'
    count: 1
  - id: '129'
    name: 'Cache: Varnish Debug Objects'
    count: 1
  - id: '136'
    name: 'Database: Oracle Wallet Note'
    count: 1
  - id: postgres_customer_dump
    name: 'Database: Postgres Customer Dump'
    count: 1
flows:
  enabled: true
  chain_length: 4
  allow_duplicates: false
  include_all_topology_pivots: false
segmentation:
  enabled: true
  density: 0.4
  items:
  - factor: 1.0
    pivot_enabled: false
    type: NAT
    count: 1
hitl:
  use_env: false
validation:
  policy: strict
  check_artifacts:
    enabled: true
    delay_seconds: 15
    strict: true
