name: dataset-mixed-application-mesh_run01
iterations: 1
seed: 1109770563
topology:
  routers: 2
  hosts: 8
services:
  enabled: true
  count: 6
  density: 1.0
  include:
  - SSH
  - HTTP
  exclude: []
traffic:
  enabled: true
  density: 0.85
  items:
  - type: TCP
    count: 2
    factor: 1.0
    pattern: continuous
    rate_kbps: 512.0
    period_s: 1.0
    jitter_pct: 10.0
    content_type: text
  - type: UDP
    count: 2
    factor: 1.0
    pattern: burst
    rate_kbps: 256.0
    period_s: 2.0
    jitter_pct: 20.0
    content_type: gibberish
vulns:
  enabled: true
  count: 3
  specific:
  - name: spring/CVE-2017-4971
    path: /Users/jcacosta/Documents/GitHub/scenarioforge/outputs/installed_vuln_catalogs/05-27-26-14-40-12-f61521/content/vulhub/spring/CVE-2017-4971/docker-compose.yml
    count: 1
  - name: php/CVE-2012-1823
    path: /Users/jcacosta/Documents/GitHub/scenarioforge/outputs/installed_vuln_catalogs/05-27-26-14-40-12-f61521/content/vulhub/php/CVE-2012-1823/docker-compose.yml
    count: 1
  - name: thinkphp/5-rce
    path: /Users/jcacosta/Documents/GitHub/scenarioforge/outputs/installed_vuln_catalogs/05-27-26-14-40-12-f61521/content/vulhub/thinkphp/5-rce/docker-compose.yml
    count: 1
flag_node_generators:
  enabled: true
  count: 3
  specific:
  - id: ssh_password_audit_workstation
    name: 'SSH: Password Audit Workstation'
    count: 1
  - id: https_token_debug_api
    name: 'HTTPS: Token Debug API'
    count: 1
  - id: https_source_secret_ci
    name: 'HTTPS: CI Source Secret'
    count: 1
flows:
  enabled: true
  chain_length: 4
  allow_duplicates: false
  include_all_topology_pivots: false
segmentation:
  enabled: true
  density: 0.45
  items: []
hitl:
  use_env: false
validation:
  policy: strict
