name: dataset-mixed-application-mesh_run02
iterations: 1
seed: 577196621
topology:
  routers: 3
  hosts: 7
services:
  enabled: true
  count: 6
  density: 1.0
  include:
  - SSH
  - HTTP
  exclude: []
traffic:
  enabled: true
  density: 0.85
  items:
  - type: TCP
    count: 2
    factor: 1.0
    pattern: continuous
    rate_kbps: 512.0
    period_s: 1.0
    jitter_pct: 10.0
    content_type: text
  - type: UDP
    count: 2
    factor: 1.0
    pattern: burst
    rate_kbps: 256.0
    period_s: 2.0
    jitter_pct: 20.0
    content_type: gibberish
vulns:
  enabled: true
  count: 4
  specific:
  - name: spring/CVE-2022-22947
    path: /Users/jcacosta/Documents/GitHub/scenarioforge/outputs/installed_vuln_catalogs/05-27-26-14-40-12-f61521/content/vulhub/spring/CVE-2022-22947/docker-compose.yml
    count: 1
  - name: php/fpm
    path: /Users/jcacosta/Documents/GitHub/scenarioforge/outputs/installed_vuln_catalogs/05-27-26-14-40-12-f61521/content/vulhub/php/fpm/docker-compose.yml
    count: 1
  - name: phpunit/CVE-2017-9841
    path: /Users/jcacosta/Documents/GitHub/scenarioforge/outputs/installed_vuln_catalogs/05-27-26-14-40-12-f61521/content/vulhub/phpunit/CVE-2017-9841/docker-compose.yml
    count: 1
  - name: php/CVE-2024-2961
    path: /Users/jcacosta/Documents/GitHub/scenarioforge/outputs/installed_vuln_catalogs/05-27-26-14-40-12-f61521/content/vulhub/php/CVE-2024-2961/docker-compose.yml
    count: 1
flag_node_generators:
  enabled: true
  count: 4
  specific:
  - id: https_directory_traversal_backups
    name: 'HTTPS: Directory Traversal Backups'
    count: 1
  - id: ssh_password_finance_terminal
    name: 'SSH: Password Finance Terminal'
    count: 1
  - id: https_login_admin_console
    name: 'HTTPS: Admin Login Console'
    count: 1
  - id: https_public_status_page
    name: 'HTTPS: Public Status Page'
    count: 1
flows:
  enabled: true
  chain_length: 4
  allow_duplicates: false
  include_all_topology_pivots: false
segmentation:
  enabled: true
  density: 0.45
  items: []
hitl:
  use_env: false
validation:
  policy: strict
