name: dataset-mixed-application-mesh_run05
iterations: 1
seed: 491604054
topology:
  routers: 3
  hosts: 7
services:
  enabled: true
  count: 6
  density: 1.0
  include:
  - SSH
  - HTTP
  exclude: []
traffic:
  enabled: true
  density: 0.85
  items:
  - type: TCP
    count: 2
    factor: 1.0
    pattern: continuous
    rate_kbps: 512.0
    period_s: 1.0
    jitter_pct: 10.0
    content_type: text
  - type: UDP
    count: 2
    factor: 1.0
    pattern: burst
    rate_kbps: 256.0
    period_s: 2.0
    jitter_pct: 20.0
    content_type: gibberish
vulns:
  enabled: true
  count: 3
  specific:
  - name: php/php_xxe
    count: 1
  - name: php/xdebug-rce
    count: 1
  - name: spring/CVE-2022-22978
    count: 1
flag_node_generators:
  enabled: true
  count: 4
  specific:
  - id: http_source_secret_repo
    name: 'HTTP: Source Secret Repository'
    count: 1
  - id: https_public_status_page
    name: 'HTTPS: Public Status Page'
    count: 1
  - id: https_sqli_invoice_portal
    name: 'HTTPS: SQLi Invoice Portal'
    count: 1
  - id: https_basic_auth_reports
    name: 'HTTPS: Basic Auth Reports'
    count: 1
flows:
  enabled: true
  chain_length: 5
  allow_duplicates: false
  include_all_topology_pivots: false
segmentation:
  enabled: true
  density: 0.45
  items:
  - factor: 1.0
    pivot_enabled: false
    type: NAT
    count: 1
hitl:
  use_env: false
validation:
  policy: strict
  check_artifacts:
    enabled: true
    delay_seconds: 15
    strict: true
