name: dataset-mixed-application-mesh_run03
iterations: 1
seed: 1132657207
topology:
  routers: 2
  hosts: 10
services:
  enabled: true
  count: 4
  density: 1.0
  include:
  - SSH
  - HTTP
  exclude: []
traffic:
  enabled: true
  density: 0.85
  items:
  - type: TCP
    count: 2
    factor: 1.0
    pattern: continuous
    rate_kbps: 512.0
    period_s: 1.0
    jitter_pct: 10.0
    content_type: text
  - type: UDP
    count: 2
    factor: 1.0
    pattern: burst
    rate_kbps: 256.0
    period_s: 2.0
    jitter_pct: 20.0
    content_type: gibberish
vulns:
  enabled: true
  count: 3
  specific:
  - name: django/CVE-2020-9402
    path: /Users/jcacosta/Documents/GitHub/scenarioforge/outputs/installed_vuln_catalogs/05-27-26-14-40-12-f61521/content/vulhub/django/CVE-2020-9402/docker-compose.yml
    count: 1
  - name: php/8.1-backdoor
    path: /Users/jcacosta/Documents/GitHub/scenarioforge/outputs/installed_vuln_catalogs/05-27-26-14-40-12-f61521/content/vulhub/php/8.1-backdoor/docker-compose.yml
    count: 1
  - name: spring/CVE-2018-1273
    path: /Users/jcacosta/Documents/GitHub/scenarioforge/outputs/installed_vuln_catalogs/05-27-26-14-40-12-f61521/content/vulhub/spring/CVE-2018-1273/docker-compose.yml
    count: 1
flag_node_generators:
  enabled: true
  count: 3
  specific:
  - id: https_sqli_invoice_portal
    name: 'HTTPS: SQLi Invoice Portal'
    count: 1
  - id: https_basic_auth_reports
    name: 'HTTPS: Basic Auth Reports'
    count: 1
  - id: ssh_key_git_deploy
    name: 'SSH: Key Git Deploy Account'
    count: 1
flows:
  enabled: true
  chain_length: 5
  allow_duplicates: false
  include_all_topology_pivots: false
segmentation:
  enabled: true
  density: 0.45
  items:
  - factor: 1.0
    pivot_enabled: false
    type: NAT
    count: 1
hitl:
  use_env: false
validation:
  policy: strict
  check_artifacts:
    enabled: true
    delay_seconds: 15
    strict: true
