name: dataset-scale-multi-artifact_run01
iterations: 1
seed: 1415523453
topology:
  routers: 4
  hosts: 11
services:
  enabled: true
  count: 5
  density: 1.0
  include:
  - SSH
  - HTTP
  exclude: []
traffic:
  enabled: true
  density: 0.85
  items:
  - type: TCP
    count: 2
    factor: 1.0
    pattern: continuous
    rate_kbps: 512.0
    period_s: 1.0
    jitter_pct: 10.0
    content_type: photo
  - type: UDP
    count: 2
    factor: 1.0
    pattern: burst
    rate_kbps: 256.0
    period_s: 2.0
    jitter_pct: 20.0
    content_type: gibberish
vulns:
  enabled: false
  count: 0
  include: []
  exclude: []
flag_node_generators:
  enabled: true
  count: 4
  specific:
  - id: dns_zone_transfer_records
    name: 'DNS: Zone Transfer Records'
    count: 1
  - id: http_cookie_role_escalation
    name: 'HTTP: Cookie Role Escalation'
    count: 1
  - id: http_public_file_drop
    name: 'HTTP: Public File Drop'
    count: 1
  - id: http_upload_file_drop
    name: 'HTTP: Upload File Drop'
    count: 1
flows:
  enabled: true
  chain_length: 3
  allow_duplicates: false
  include_all_topology_pivots: true
segmentation:
  enabled: true
  density: 0.45
  accessible_by_pivot: true
  items:
  - factor: 1.0
    pivot_enabled: true
    pivot_provider: flag-node-generator
    type: Firewall
    count: 1
hitl:
  use_env: false
validation:
  policy: strict
  check_artifacts:
    enabled: true
    delay_seconds: 15
    strict: true
