name: dataset-catalog-coverage-030
iterations: 1
seed: 1038737727
topology:
  routers: 1
  hosts: 6
services:
  enabled: true
  count: 4
  density: 1.0
  include:
  - SSH
  - HTTP
  exclude: []
traffic:
  enabled: true
  density: 0.35
  items:
  - type: TCP
    count: 1
    factor: 1.0
    pattern: periodic
    rate_kbps: 32.0
    period_s: 5.0
    jitter_pct: 10.0
    content_type: text
vulns:
  enabled: true
  count: 3
  specific:
  - name: imagemagick/CVE-2020-29599
    path: /Users/jcacosta/Documents/GitHub/scenarioforge/outputs/installed_vuln_catalogs/05-27-26-14-40-12-f61521/content/vulhub/imagemagick/CVE-2020-29599/docker-compose.yml
    count: 1
  - name: imagemagick/CVE-2022-44268
    path: /Users/jcacosta/Documents/GitHub/scenarioforge/outputs/installed_vuln_catalogs/05-27-26-14-40-12-f61521/content/vulhub/imagemagick/CVE-2022-44268/docker-compose.yml
    count: 1
  - name: influxdb/CVE-2019-20933
    path: /Users/jcacosta/Documents/GitHub/scenarioforge/outputs/installed_vuln_catalogs/05-27-26-14-40-12-f61521/content/vulhub/influxdb/CVE-2019-20933/docker-compose.yml
    count: 1
flag_node_generators:
  enabled: true
  count: 1
  specific:
  - id: '129'
    name: 'Cache: Varnish Debug Objects'
    count: 1
flows:
  enabled: true
  chain_length: 4
  allow_duplicates: false
  include_all_topology_pivots: true
segmentation:
  enabled: true
  density: 0.35
  items:
  - type: Firewall
    count: 1
    factor: 1.0
    pivot_enabled: true
  - type: NAT
    count: 1
    factor: 1.0
    pivot_enabled: false
hitl:
  use_env: false
validation:
  policy: strict
