name: dataset-catalog-coverage-076
iterations: 1
seed: 290062843
topology:
  routers: 2
  hosts: 10
services:
  enabled: true
  count: 2
  density: 1.0
  include:
  - SSH
  - HTTP
  exclude: []
traffic:
  enabled: true
  density: 0.6
  items:
  - type: TCP
    count: 1
    factor: 1.0
    pattern: continuous
    rate_kbps: 128.0
    period_s: 2.0
    jitter_pct: 15.0
    content_type: photo
  - type: UDP
    count: 1
    factor: 1.0
    pattern: periodic
    rate_kbps: 64.0
    period_s: 5.0
    jitter_pct: 25.0
    content_type: audio
vulns:
  enabled: true
  count: 3
  specific:
  - name: zabbix/CVE-2016-10134
    path: /Users/jcacosta/Documents/GitHub/scenarioforge/outputs/installed_vuln_catalogs/05-27-26-14-40-12-f61521/content/vulhub/zabbix/CVE-2016-10134/docker-compose.yml
    count: 1
  - name: zabbix/CVE-2017-2824
    path: /Users/jcacosta/Documents/GitHub/scenarioforge/outputs/installed_vuln_catalogs/05-27-26-14-40-12-f61521/content/vulhub/zabbix/CVE-2017-2824/docker-compose.yml
    count: 1
  - name: zabbix/CVE-2020-11800
    path: /Users/jcacosta/Documents/GitHub/scenarioforge/outputs/installed_vuln_catalogs/05-27-26-14-40-12-f61521/content/vulhub/zabbix/CVE-2020-11800/docker-compose.yml
    count: 1
flag_node_generators:
  enabled: true
  count: 1
  specific:
  - id: ldap_bind_service_account
    name: 'LDAP: Service Account Bind'
    count: 1
flows:
  enabled: true
  chain_length: 2
  allow_duplicates: false
  include_all_topology_pivots: false
segmentation:
  enabled: true
  density: 0.44999999999999996
  items:
  - type: Firewall
    count: 1
    factor: 1.0
    pivot_enabled: false
  - type: NAT
    count: 1
    factor: 1.0
    pivot_enabled: false
hitl:
  use_env: false
validation:
  policy: strict
