name: "massive-randomness"
topology:
  type: "mesh"
  routers: [2, 6]
  hosts: [10, 18]
  randomize: true
services:
  randomize: true
vulns:
  randomize: true
  count: [5, 15]
flows:
  randomize: true
